---@meta
error("cannot import meta file")
---
---@alias Grid Row[]
---@alias Row integer[]
---
---@class ConwaySetupOpts Options for running the game of life in neovim
---@field on_char string?
---@field off_char string?
---@field update_interval_ms integer?
---@field chance number?
